### ISSUE TITLE
Clean up translations in consentAdmin

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp-module-consentadmin#1]
Fixes https://github.com/simplesamlphp/simplesamlphp/issues/455 and https://github.com/simplesamlphp/simplesamlphp/issues/464

``
-bash-4.2$ grep -R "getTag"
www/consentAdmin.php:$sp_empty_description = $translator->getTag('sp_empty_description');
www/consentAdmin.php:    $sp_name = $translator->getPreferredTranslation($translator->getTag('spname'));
www/consentAdmin.php:    $sp_description = $translator->getPreferredTranslation($translator->getTag('spdescription'));
``

``
-bash-4.2$ grep -R "includeLanguageFile"
www/consentAdmin.php:$translator->includeLanguageFile('attributes'); // attribute listings translated by this dictionary
``

``
-bash-4.2$ grep -R "includeInlineTranslation"
www/consentAdmin.php:    $translator->includeInlineTranslation('spname', $sp_name);
www/consentAdmin.php:    $translator->includeInlineTranslation('spdescription', $sp_description);
``

``
-bash-4.2$ grep -R "getAttributeTranslation"
www/consentAdmin.php:        $name = $translator->getAttributeTranslation(strtolower($orig_name)); // translate
``

**Comment by clmcavaney** [comment]
G'day @tvdijen - just checking is this module not functioning for SSP v2.x?  It looks like it is still using the older translation system.

**Comment by tvdijen** [comment]
These issues have been resolved a while ago, so closing this.
The module should work fine on SSP 2.x
